sudo: false

language: node_js

cache:
  directories:
    - ~/.npm

node_js:
  - 10
  # - 9
  # - 8

install: npm install

script:
  - npm run react-cli
  - ENTER

after_success: echo "Success"

branches:
  only: master
