sudo: false

language: node_js

cache:
  directories:
    - ~/.npm

node_js:
  - 10
  - 9
  - 8

os:
  - linux
  - osx
  - windows

install: npm install

script:
  - npm run react-cli
  - ^[[B
  -

after_success: echo "Success"

branches:
  only: master
